# Generated by Django 2.0.1 on 2018-11-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excludespage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_page', models.CharField(default='None', max_length=100, verbose_name='Исключающие страницу')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.CreateModel(
            name='Excludestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_state', models.CharField(default='None', max_length=100, verbose_name='Исключающие предложение')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
